"""set_default_character_slots_for_existing_users

Revision ID: 18052f65c6d7
Revises: 7ee092123de1
Create Date: 2025-10-16 23:14:27.231060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18052f65c6d7'
down_revision = '7ee092123de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Set default value of 3 for existing users with NULL character_slots
    op.execute("UPDATE players SET character_slots = 3 WHERE character_slots IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # This downgrade is not reversible as we can't distinguish original NULLs
    pass
    # ### end Alembic commands ###
