"""Add currency fields to characters table

Revision ID: 271edf63026a
Revises: c83f86c5d192
Create Date: 2025-10-04 12:38:40.395241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271edf63026a'
down_revision = 'c83f86c5d192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gold', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('silver', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('copper', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('copper')
        batch_op.drop_column('silver')
        batch_op.drop_column('gold')

    # ### end Alembic commands ###
