"""Add icon_path to item_templates

Revision ID: 3b0dab005587
Revises: 74ccd4ec580c
Create Date: 2025-10-21 11:14:02.662517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '3b0dab005587'
down_revision = '74ccd4ec580c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_items')
    with op.batch_alter_table('item_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('weight_reduction', sa.Float(), nullable=True))
        batch_op.alter_column('item_type',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'13'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_templates', schema=None) as batch_op:
        batch_op.alter_column('item_type',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'13'"))
        batch_op.drop_column('weight_reduction')
        batch_op.drop_column('icon_path')

    op.create_table('_alembic_tmp_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('template_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('condition', sa.INTEGER(), nullable=True),
    sa.Column('quality_modifier', sa.FLOAT(), nullable=True),
    sa.Column('components_used', sqlite.JSON(), nullable=True),
    sa.Column('recipe_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('disassemble_yield', sqlite.JSON(), nullable=True),
    sa.Column('owner_character_id', sa.INTEGER(), nullable=True),
    sa.Column('equipped_character_id', sa.INTEGER(), nullable=True),
    sa.Column('room_id', sa.INTEGER(), nullable=True),
    sa.Column('container_id', sa.INTEGER(), nullable=True),
    sa.Column('modifications', sqlite.JSON(), nullable=True),
    sa.Column('enchantments', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('current_durability', sa.INTEGER(), nullable=True),
    sa.Column('sockets', sqlite.JSON(), nullable=True),
    sa.Column('sharpness', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('balance', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('custom_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('custom_flags', sqlite.JSON(), nullable=True),
    sa.Column('crafted_by_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('equipped_slot', sa.VARCHAR(length=50), nullable=True),
    sa.Column('last_repaired_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['container_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['equipped_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['owner_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['item_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
