"""Initial migration

Revision ID: 7409a993b5d0
Revises: 
Create Date: 2025-10-04 11:28:47.156009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7409a993b5d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level_range', sa.JSON(), nullable=True),
    sa.Column('entry_requirements', sa.JSON(), nullable=True),
    sa.Column('environmental_effects', sa.JSON(), nullable=True),
    sa.Column('connected_areas', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_areas_area_id'), ['area_id'], unique=True)

    op.create_table('item_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_type', sa.String(length=100), nullable=False),
    sa.Column('subtype', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('quality_tier', sa.String(length=20), nullable=True),
    sa.Column('components_required', sa.JSON(), nullable=True),
    sa.Column('disassembly_data', sa.JSON(), nullable=True),
    sa.Column('equipment_stats', sa.JSON(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_templates_template_id'), ['template_id'], unique=True)

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_players_username'), ['username'], unique=True)

    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('max_level', sa.Integer(), nullable=True),
    sa.Column('attribute_requirements', sa.JSON(), nullable=True),
    sa.Column('cost_formula', sa.String(length=100), nullable=True),
    sa.Column('governs', sa.JSON(), nullable=True),
    sa.Column('related_skills', sa.JSON(), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('unlock_conditions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_skill_id'), ['skill_id'], unique=True)

    op.create_table('spells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spell_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('school', sa.String(length=50), nullable=False),
    sa.Column('mana_cost', sa.Integer(), nullable=True),
    sa.Column('cast_time', sa.Float(), nullable=True),
    sa.Column('cooldown', sa.Float(), nullable=True),
    sa.Column('range', sa.Integer(), nullable=True),
    sa.Column('attribute_requirements', sa.JSON(), nullable=True),
    sa.Column('skill_requirements', sa.JSON(), nullable=True),
    sa.Column('progress_point_cost', sa.Integer(), nullable=True),
    sa.Column('effects', sa.JSON(), nullable=True),
    sa.Column('target_type', sa.String(length=20), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('unlock_conditions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spells', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spells_spell_id'), ['spell_id'], unique=True)

    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(length=100), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('x_coord', sa.Integer(), nullable=True),
    sa.Column('y_coord', sa.Integer(), nullable=True),
    sa.Column('z_coord', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('exits', sa.JSON(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('npcs', sa.JSON(), nullable=True),
    sa.Column('lighting', sa.String(length=20), nullable=True),
    sa.Column('temperature', sa.String(length=20), nullable=True),
    sa.Column('weather_effects', sa.JSON(), nullable=True),
    sa.Column('is_safe', sa.Boolean(), nullable=True),
    sa.Column('is_indoors', sa.Boolean(), nullable=True),
    sa.Column('is_water', sa.Boolean(), nullable=True),
    sa.Column('is_air', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_room_id'), ['room_id'], unique=True)

    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_played', sa.DateTime(), nullable=True),
    sa.Column('current_room_id', sa.Integer(), nullable=True),
    sa.Column('x_coord', sa.Integer(), nullable=True),
    sa.Column('y_coord', sa.Integer(), nullable=True),
    sa.Column('z_coord', sa.Integer(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('max_hp', sa.Integer(), nullable=True),
    sa.Column('current_hp', sa.Integer(), nullable=True),
    sa.Column('max_mana', sa.Integer(), nullable=True),
    sa.Column('current_mana', sa.Integer(), nullable=True),
    sa.Column('max_movement', sa.Integer(), nullable=True),
    sa.Column('current_movement', sa.Integer(), nullable=True),
    sa.Column('trial_points', sa.Integer(), nullable=True),
    sa.Column('progress_points', sa.Integer(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('spells', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['current_room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_characters_name'), ['name'], unique=True)

    op.create_table('character_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('experience_to_next', sa.Integer(), nullable=True),
    sa.Column('learned_at', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_spells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('times_cast', sa.Integer(), nullable=True),
    sa.Column('last_cast', sa.DateTime(), nullable=True),
    sa.Column('learned_at', sa.DateTime(), nullable=True),
    sa.Column('learned_from', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['spells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition', sa.Integer(), nullable=True),
    sa.Column('quality_modifier', sa.Float(), nullable=True),
    sa.Column('components_used', sa.JSON(), nullable=True),
    sa.Column('recipe_id', sa.String(length=100), nullable=True),
    sa.Column('disassemble_yield', sa.JSON(), nullable=True),
    sa.Column('owner_character_id', sa.Integer(), nullable=True),
    sa.Column('equipped_character_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('container_id', sa.Integer(), nullable=True),
    sa.Column('modifications', sa.JSON(), nullable=True),
    sa.Column('enchantments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['container_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['equipped_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['owner_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['item_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.drop_table('character_spells')
    op.drop_table('character_skills')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_characters_name'))

    op.drop_table('characters')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_room_id'))

    op.drop_table('rooms')
    with op.batch_alter_table('spells', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spells_spell_id'))

    op.drop_table('spells')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_skill_id'))

    op.drop_table('skills')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_username'))
        batch_op.drop_index(batch_op.f('ix_players_email'))

    op.drop_table('players')
    with op.batch_alter_table('item_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_templates_template_id'))

    op.drop_table('item_templates')
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_areas_area_id'))

    op.drop_table('areas')
    # ### end Alembic commands ###
