"""add_avatar_field_to_characters_table

Revision ID: 7474fba7d73d
Revises: f1g2h3i4j5k6
Create Date: 2025-10-16 20:18:51.630824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7474fba7d73d'
down_revision = 'f1g2h3i4j5k6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('avatar', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'avatar')
    # ### end Alembic commands ###
