"""add_character_slots_field_to_players_table

Revision ID: 7ee092123de1
Revises: 9fe464741d19
Create Date: 2025-10-16 23:11:17.978713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee092123de1'
down_revision = '9fe464741d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('character_slots', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'character_slots')
    # ### end Alembic commands ###
