"""Add bag_slots to characters

Revision ID: 7feb7c1dcc0f
Revises: 3b0dab005587
Create Date: 2025-10-21 11:36:47.971124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7feb7c1dcc0f'
down_revision = '3b0dab005587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bag_slots', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('bag_slots')

    # ### end Alembic commands ###
