"""add_account_points_field_to_players_table

Revision ID: 9fe464741d19
Revises: 7474fba7d73d
Create Date: 2025-10-16 22:58:49.104026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe464741d19'
down_revision = '7474fba7d73d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('account_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'account_points')
    # ### end Alembic commands ###
